dns:
  enable: true # 是否启用dns false
  ipv6: true
  use-hosts: true
  prefer-h3: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip # 模式：redir-host或fake-ip
  fake-ip-range: 198.18.0.1/16 #
  fake-ip-filter: # fake ip 白名单列表，如果你不知道这个参数的作用，请勿修改
    - '*.lan'
    - localhost.ptlogin2.qq.com
  nameserver:
    - https://1.1.1.1/dns-query
  nameserver-policy:
    "geosite:cn,private":
    - https://223.5.5.5/dns-query
